#config_version=6

# Base mode that starts at the beginning of each ball
# and stops at the end of each ball.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

event_player:
  mode_base_started:
    - start_mode_bumpers
  mode_base_will_stop:
    - stop_mode_bumpers
  left_lane_hit: start_mode_hurryup

shots:
  left_lane:
    switches: s_left_lane

slide_player:
  mode_base_started: base_slide